"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CuotasPagadasEntity = void 0;
const typeorm_1 = require("typeorm");
let CuotasPagadasEntity = (() => {
    let _classDecorators = [(0, typeorm_1.ViewEntity)({ schema: 'ADCC', name: 'CBI_CUOTAS_PAGADAS_V' })];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _idFraccion_decorators;
    let _idFraccion_initializers = [];
    let _idFraccion_extraInitializers = [];
    let _nombreFraccion_decorators;
    let _nombreFraccion_initializers = [];
    let _nombreFraccion_extraInitializers = [];
    let _idManzana_decorators;
    let _idManzana_initializers = [];
    let _idManzana_extraInitializers = [];
    let _idLote_decorators;
    let _idLote_initializers = [];
    let _idLote_extraInitializers = [];
    let _numeroContrato_decorators;
    let _numeroContrato_initializers = [];
    let _numeroContrato_extraInitializers = [];
    let _sucursal_decorators;
    let _sucursal_initializers = [];
    let _sucursal_extraInitializers = [];
    let _nombreParaDocumento_decorators;
    let _nombreParaDocumento_initializers = [];
    let _nombreParaDocumento_extraInitializers = [];
    let _idCliente_decorators;
    let _idCliente_initializers = [];
    let _idCliente_extraInitializers = [];
    let _documento_decorators;
    let _documento_initializers = [];
    let _documento_extraInitializers = [];
    let _numeroCuota_decorators;
    let _numeroCuota_initializers = [];
    let _numeroCuota_extraInitializers = [];
    let _totalCuotas_decorators;
    let _totalCuotas_initializers = [];
    let _totalCuotas_extraInitializers = [];
    let _estadoActualContrato_decorators;
    let _estadoActualContrato_initializers = [];
    let _estadoActualContrato_extraInitializers = [];
    let _montoCuota_decorators;
    let _montoCuota_initializers = [];
    let _montoCuota_extraInitializers = [];
    let _moraCuota_decorators;
    let _moraCuota_initializers = [];
    let _moraCuota_extraInitializers = [];
    let _fechaVencimiento_decorators;
    let _fechaVencimiento_initializers = [];
    let _fechaVencimiento_extraInitializers = [];
    let _mesesMora_decorators;
    let _mesesMora_initializers = [];
    let _mesesMora_extraInitializers = [];
    let _interesCobrado_decorators;
    let _interesCobrado_initializers = [];
    let _interesCobrado_extraInitializers = [];
    let _descuentoInteres_decorators;
    let _descuentoInteres_initializers = [];
    let _descuentoInteres_extraInitializers = [];
    let _cuotaCobrada_decorators;
    let _cuotaCobrada_initializers = [];
    let _cuotaCobrada_extraInitializers = [];
    let _notaCred_decorators;
    let _notaCred_initializers = [];
    let _notaCred_extraInitializers = [];
    let _telefonoCelular_decorators;
    let _telefonoCelular_initializers = [];
    let _telefonoCelular_extraInitializers = [];
    let _fechaPago_decorators;
    let _fechaPago_initializers = [];
    let _fechaPago_extraInitializers = [];
    let _moneda_decorators;
    let _moneda_initializers = [];
    let _moneda_extraInitializers = [];
    let _nroFactura_decorators;
    let _nroFactura_initializers = [];
    let _nroFactura_extraInitializers = [];
    let _formaPago_decorators;
    let _formaPago_initializers = [];
    let _formaPago_extraInitializers = [];
    let _fecContrato_decorators;
    let _fecContrato_initializers = [];
    let _fecContrato_extraInitializers = [];
    let _fecTrato_decorators;
    let _fecTrato_initializers = [];
    let _fecTrato_extraInitializers = [];
    let _vendedor_decorators;
    let _vendedor_initializers = [];
    let _vendedor_extraInitializers = [];
    let _planPagoVendedor_decorators;
    let _planPagoVendedor_initializers = [];
    let _planPagoVendedor_extraInitializers = [];
    let _refinanciacion_decorators;
    let _refinanciacion_initializers = [];
    let _refinanciacion_extraInitializers = [];
    let _cancelacionAnticipada_decorators;
    let _cancelacionAnticipada_initializers = [];
    let _cancelacionAnticipada_extraInitializers = [];
    var CuotasPagadasEntity = _classThis = class {
        constructor() {
            this.idFraccion = __runInitializers(this, _idFraccion_initializers, void 0);
            this.nombreFraccion = (__runInitializers(this, _idFraccion_extraInitializers), __runInitializers(this, _nombreFraccion_initializers, void 0));
            this.idManzana = (__runInitializers(this, _nombreFraccion_extraInitializers), __runInitializers(this, _idManzana_initializers, void 0));
            this.idLote = (__runInitializers(this, _idManzana_extraInitializers), __runInitializers(this, _idLote_initializers, void 0));
            this.numeroContrato = (__runInitializers(this, _idLote_extraInitializers), __runInitializers(this, _numeroContrato_initializers, void 0));
            this.sucursal = (__runInitializers(this, _numeroContrato_extraInitializers), __runInitializers(this, _sucursal_initializers, void 0));
            this.nombreParaDocumento = (__runInitializers(this, _sucursal_extraInitializers), __runInitializers(this, _nombreParaDocumento_initializers, void 0));
            this.idCliente = (__runInitializers(this, _nombreParaDocumento_extraInitializers), __runInitializers(this, _idCliente_initializers, void 0));
            this.documento = (__runInitializers(this, _idCliente_extraInitializers), __runInitializers(this, _documento_initializers, void 0));
            this.numeroCuota = (__runInitializers(this, _documento_extraInitializers), __runInitializers(this, _numeroCuota_initializers, void 0));
            this.totalCuotas = (__runInitializers(this, _numeroCuota_extraInitializers), __runInitializers(this, _totalCuotas_initializers, void 0));
            this.estadoActualContrato = (__runInitializers(this, _totalCuotas_extraInitializers), __runInitializers(this, _estadoActualContrato_initializers, void 0));
            this.montoCuota = (__runInitializers(this, _estadoActualContrato_extraInitializers), __runInitializers(this, _montoCuota_initializers, void 0));
            this.moraCuota = (__runInitializers(this, _montoCuota_extraInitializers), __runInitializers(this, _moraCuota_initializers, void 0));
            this.fechaVencimiento = (__runInitializers(this, _moraCuota_extraInitializers), __runInitializers(this, _fechaVencimiento_initializers, void 0));
            this.mesesMora = (__runInitializers(this, _fechaVencimiento_extraInitializers), __runInitializers(this, _mesesMora_initializers, void 0));
            this.interesCobrado = (__runInitializers(this, _mesesMora_extraInitializers), __runInitializers(this, _interesCobrado_initializers, void 0));
            this.descuentoInteres = (__runInitializers(this, _interesCobrado_extraInitializers), __runInitializers(this, _descuentoInteres_initializers, void 0));
            this.cuotaCobrada = (__runInitializers(this, _descuentoInteres_extraInitializers), __runInitializers(this, _cuotaCobrada_initializers, void 0));
            this.notaCred = (__runInitializers(this, _cuotaCobrada_extraInitializers), __runInitializers(this, _notaCred_initializers, void 0));
            this.telefonoCelular = (__runInitializers(this, _notaCred_extraInitializers), __runInitializers(this, _telefonoCelular_initializers, void 0));
            this.fechaPago = (__runInitializers(this, _telefonoCelular_extraInitializers), __runInitializers(this, _fechaPago_initializers, void 0));
            this.moneda = (__runInitializers(this, _fechaPago_extraInitializers), __runInitializers(this, _moneda_initializers, void 0));
            this.nroFactura = (__runInitializers(this, _moneda_extraInitializers), __runInitializers(this, _nroFactura_initializers, void 0));
            this.formaPago = (__runInitializers(this, _nroFactura_extraInitializers), __runInitializers(this, _formaPago_initializers, void 0));
            this.fecContrato = (__runInitializers(this, _formaPago_extraInitializers), __runInitializers(this, _fecContrato_initializers, void 0));
            this.fecTrato = (__runInitializers(this, _fecContrato_extraInitializers), __runInitializers(this, _fecTrato_initializers, void 0));
            this.vendedor = (__runInitializers(this, _fecTrato_extraInitializers), __runInitializers(this, _vendedor_initializers, void 0));
            this.planPagoVendedor = (__runInitializers(this, _vendedor_extraInitializers), __runInitializers(this, _planPagoVendedor_initializers, void 0));
            this.refinanciacion = (__runInitializers(this, _planPagoVendedor_extraInitializers), __runInitializers(this, _refinanciacion_initializers, void 0));
            this.cancelacionAnticipada = (__runInitializers(this, _refinanciacion_extraInitializers), __runInitializers(this, _cancelacionAnticipada_initializers, void 0));
            __runInitializers(this, _cancelacionAnticipada_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "CuotasPagadasEntity");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _idFraccion_decorators = [(0, typeorm_1.ViewColumn)({ name: 'ID_FRACCION' })];
        _nombreFraccion_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NOMBRE_FRACCION' })];
        _idManzana_decorators = [(0, typeorm_1.ViewColumn)({ name: 'ID_MANZANA' })];
        _idLote_decorators = [(0, typeorm_1.ViewColumn)({ name: 'ID_LOTE' })];
        _numeroContrato_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NUMERO_CONTRATO' })];
        _sucursal_decorators = [(0, typeorm_1.ViewColumn)({ name: 'SUCURSAL' })];
        _nombreParaDocumento_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NOMBRE_PARA_DOCUMENTO' })];
        _idCliente_decorators = [(0, typeorm_1.ViewColumn)({ name: 'ID_CLIENTE' })];
        _documento_decorators = [(0, typeorm_1.ViewColumn)({ name: 'DOCUMENTO' })];
        _numeroCuota_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NUMERO_CUOTA' })];
        _totalCuotas_decorators = [(0, typeorm_1.ViewColumn)({ name: 'TOTAL_CUOTAS' })];
        _estadoActualContrato_decorators = [(0, typeorm_1.ViewColumn)({ name: 'ESTADO_ACTUAL_CONTRATO' })];
        _montoCuota_decorators = [(0, typeorm_1.ViewColumn)({ name: 'MONTO_CUOTA' })];
        _moraCuota_decorators = [(0, typeorm_1.ViewColumn)({ name: 'MORA_CUOTA' })];
        _fechaVencimiento_decorators = [(0, typeorm_1.ViewColumn)({ name: 'FECHA_VENCIMIENTO' })];
        _mesesMora_decorators = [(0, typeorm_1.ViewColumn)({ name: 'MESES_MORA' })];
        _interesCobrado_decorators = [(0, typeorm_1.ViewColumn)({ name: 'INTERES_COBRADO' })];
        _descuentoInteres_decorators = [(0, typeorm_1.ViewColumn)({ name: 'DESCUENTO_INTERES' })];
        _cuotaCobrada_decorators = [(0, typeorm_1.ViewColumn)({ name: 'CUOTA_COBRADA' })];
        _notaCred_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NOTA_CRED' })];
        _telefonoCelular_decorators = [(0, typeorm_1.ViewColumn)({ name: 'TELEFONO_CELULAR' })];
        _fechaPago_decorators = [(0, typeorm_1.ViewColumn)({ name: 'FECHA_PAGO' })];
        _moneda_decorators = [(0, typeorm_1.ViewColumn)({ name: 'MONEDA' })];
        _nroFactura_decorators = [(0, typeorm_1.ViewColumn)({ name: 'NRO_FACTURA' })];
        _formaPago_decorators = [(0, typeorm_1.ViewColumn)({ name: 'FORMA_PAGO' })];
        _fecContrato_decorators = [(0, typeorm_1.ViewColumn)({ name: 'FEC_CONTRATO' })];
        _fecTrato_decorators = [(0, typeorm_1.ViewColumn)({ name: 'FEC_TRATO' })];
        _vendedor_decorators = [(0, typeorm_1.ViewColumn)({ name: 'VENDEDOR' })];
        _planPagoVendedor_decorators = [(0, typeorm_1.ViewColumn)({ name: 'PLAN_PAGO_VENDEDOR' })];
        _refinanciacion_decorators = [(0, typeorm_1.ViewColumn)({ name: 'REFINANCIACION' })];
        _cancelacionAnticipada_decorators = [(0, typeorm_1.ViewColumn)({ name: 'CANCELACION_ANTICIPADA' })];
        __esDecorate(null, null, _idFraccion_decorators, { kind: "field", name: "idFraccion", static: false, private: false, access: { has: obj => "idFraccion" in obj, get: obj => obj.idFraccion, set: (obj, value) => { obj.idFraccion = value; } }, metadata: _metadata }, _idFraccion_initializers, _idFraccion_extraInitializers);
        __esDecorate(null, null, _nombreFraccion_decorators, { kind: "field", name: "nombreFraccion", static: false, private: false, access: { has: obj => "nombreFraccion" in obj, get: obj => obj.nombreFraccion, set: (obj, value) => { obj.nombreFraccion = value; } }, metadata: _metadata }, _nombreFraccion_initializers, _nombreFraccion_extraInitializers);
        __esDecorate(null, null, _idManzana_decorators, { kind: "field", name: "idManzana", static: false, private: false, access: { has: obj => "idManzana" in obj, get: obj => obj.idManzana, set: (obj, value) => { obj.idManzana = value; } }, metadata: _metadata }, _idManzana_initializers, _idManzana_extraInitializers);
        __esDecorate(null, null, _idLote_decorators, { kind: "field", name: "idLote", static: false, private: false, access: { has: obj => "idLote" in obj, get: obj => obj.idLote, set: (obj, value) => { obj.idLote = value; } }, metadata: _metadata }, _idLote_initializers, _idLote_extraInitializers);
        __esDecorate(null, null, _numeroContrato_decorators, { kind: "field", name: "numeroContrato", static: false, private: false, access: { has: obj => "numeroContrato" in obj, get: obj => obj.numeroContrato, set: (obj, value) => { obj.numeroContrato = value; } }, metadata: _metadata }, _numeroContrato_initializers, _numeroContrato_extraInitializers);
        __esDecorate(null, null, _sucursal_decorators, { kind: "field", name: "sucursal", static: false, private: false, access: { has: obj => "sucursal" in obj, get: obj => obj.sucursal, set: (obj, value) => { obj.sucursal = value; } }, metadata: _metadata }, _sucursal_initializers, _sucursal_extraInitializers);
        __esDecorate(null, null, _nombreParaDocumento_decorators, { kind: "field", name: "nombreParaDocumento", static: false, private: false, access: { has: obj => "nombreParaDocumento" in obj, get: obj => obj.nombreParaDocumento, set: (obj, value) => { obj.nombreParaDocumento = value; } }, metadata: _metadata }, _nombreParaDocumento_initializers, _nombreParaDocumento_extraInitializers);
        __esDecorate(null, null, _idCliente_decorators, { kind: "field", name: "idCliente", static: false, private: false, access: { has: obj => "idCliente" in obj, get: obj => obj.idCliente, set: (obj, value) => { obj.idCliente = value; } }, metadata: _metadata }, _idCliente_initializers, _idCliente_extraInitializers);
        __esDecorate(null, null, _documento_decorators, { kind: "field", name: "documento", static: false, private: false, access: { has: obj => "documento" in obj, get: obj => obj.documento, set: (obj, value) => { obj.documento = value; } }, metadata: _metadata }, _documento_initializers, _documento_extraInitializers);
        __esDecorate(null, null, _numeroCuota_decorators, { kind: "field", name: "numeroCuota", static: false, private: false, access: { has: obj => "numeroCuota" in obj, get: obj => obj.numeroCuota, set: (obj, value) => { obj.numeroCuota = value; } }, metadata: _metadata }, _numeroCuota_initializers, _numeroCuota_extraInitializers);
        __esDecorate(null, null, _totalCuotas_decorators, { kind: "field", name: "totalCuotas", static: false, private: false, access: { has: obj => "totalCuotas" in obj, get: obj => obj.totalCuotas, set: (obj, value) => { obj.totalCuotas = value; } }, metadata: _metadata }, _totalCuotas_initializers, _totalCuotas_extraInitializers);
        __esDecorate(null, null, _estadoActualContrato_decorators, { kind: "field", name: "estadoActualContrato", static: false, private: false, access: { has: obj => "estadoActualContrato" in obj, get: obj => obj.estadoActualContrato, set: (obj, value) => { obj.estadoActualContrato = value; } }, metadata: _metadata }, _estadoActualContrato_initializers, _estadoActualContrato_extraInitializers);
        __esDecorate(null, null, _montoCuota_decorators, { kind: "field", name: "montoCuota", static: false, private: false, access: { has: obj => "montoCuota" in obj, get: obj => obj.montoCuota, set: (obj, value) => { obj.montoCuota = value; } }, metadata: _metadata }, _montoCuota_initializers, _montoCuota_extraInitializers);
        __esDecorate(null, null, _moraCuota_decorators, { kind: "field", name: "moraCuota", static: false, private: false, access: { has: obj => "moraCuota" in obj, get: obj => obj.moraCuota, set: (obj, value) => { obj.moraCuota = value; } }, metadata: _metadata }, _moraCuota_initializers, _moraCuota_extraInitializers);
        __esDecorate(null, null, _fechaVencimiento_decorators, { kind: "field", name: "fechaVencimiento", static: false, private: false, access: { has: obj => "fechaVencimiento" in obj, get: obj => obj.fechaVencimiento, set: (obj, value) => { obj.fechaVencimiento = value; } }, metadata: _metadata }, _fechaVencimiento_initializers, _fechaVencimiento_extraInitializers);
        __esDecorate(null, null, _mesesMora_decorators, { kind: "field", name: "mesesMora", static: false, private: false, access: { has: obj => "mesesMora" in obj, get: obj => obj.mesesMora, set: (obj, value) => { obj.mesesMora = value; } }, metadata: _metadata }, _mesesMora_initializers, _mesesMora_extraInitializers);
        __esDecorate(null, null, _interesCobrado_decorators, { kind: "field", name: "interesCobrado", static: false, private: false, access: { has: obj => "interesCobrado" in obj, get: obj => obj.interesCobrado, set: (obj, value) => { obj.interesCobrado = value; } }, metadata: _metadata }, _interesCobrado_initializers, _interesCobrado_extraInitializers);
        __esDecorate(null, null, _descuentoInteres_decorators, { kind: "field", name: "descuentoInteres", static: false, private: false, access: { has: obj => "descuentoInteres" in obj, get: obj => obj.descuentoInteres, set: (obj, value) => { obj.descuentoInteres = value; } }, metadata: _metadata }, _descuentoInteres_initializers, _descuentoInteres_extraInitializers);
        __esDecorate(null, null, _cuotaCobrada_decorators, { kind: "field", name: "cuotaCobrada", static: false, private: false, access: { has: obj => "cuotaCobrada" in obj, get: obj => obj.cuotaCobrada, set: (obj, value) => { obj.cuotaCobrada = value; } }, metadata: _metadata }, _cuotaCobrada_initializers, _cuotaCobrada_extraInitializers);
        __esDecorate(null, null, _notaCred_decorators, { kind: "field", name: "notaCred", static: false, private: false, access: { has: obj => "notaCred" in obj, get: obj => obj.notaCred, set: (obj, value) => { obj.notaCred = value; } }, metadata: _metadata }, _notaCred_initializers, _notaCred_extraInitializers);
        __esDecorate(null, null, _telefonoCelular_decorators, { kind: "field", name: "telefonoCelular", static: false, private: false, access: { has: obj => "telefonoCelular" in obj, get: obj => obj.telefonoCelular, set: (obj, value) => { obj.telefonoCelular = value; } }, metadata: _metadata }, _telefonoCelular_initializers, _telefonoCelular_extraInitializers);
        __esDecorate(null, null, _fechaPago_decorators, { kind: "field", name: "fechaPago", static: false, private: false, access: { has: obj => "fechaPago" in obj, get: obj => obj.fechaPago, set: (obj, value) => { obj.fechaPago = value; } }, metadata: _metadata }, _fechaPago_initializers, _fechaPago_extraInitializers);
        __esDecorate(null, null, _moneda_decorators, { kind: "field", name: "moneda", static: false, private: false, access: { has: obj => "moneda" in obj, get: obj => obj.moneda, set: (obj, value) => { obj.moneda = value; } }, metadata: _metadata }, _moneda_initializers, _moneda_extraInitializers);
        __esDecorate(null, null, _nroFactura_decorators, { kind: "field", name: "nroFactura", static: false, private: false, access: { has: obj => "nroFactura" in obj, get: obj => obj.nroFactura, set: (obj, value) => { obj.nroFactura = value; } }, metadata: _metadata }, _nroFactura_initializers, _nroFactura_extraInitializers);
        __esDecorate(null, null, _formaPago_decorators, { kind: "field", name: "formaPago", static: false, private: false, access: { has: obj => "formaPago" in obj, get: obj => obj.formaPago, set: (obj, value) => { obj.formaPago = value; } }, metadata: _metadata }, _formaPago_initializers, _formaPago_extraInitializers);
        __esDecorate(null, null, _fecContrato_decorators, { kind: "field", name: "fecContrato", static: false, private: false, access: { has: obj => "fecContrato" in obj, get: obj => obj.fecContrato, set: (obj, value) => { obj.fecContrato = value; } }, metadata: _metadata }, _fecContrato_initializers, _fecContrato_extraInitializers);
        __esDecorate(null, null, _fecTrato_decorators, { kind: "field", name: "fecTrato", static: false, private: false, access: { has: obj => "fecTrato" in obj, get: obj => obj.fecTrato, set: (obj, value) => { obj.fecTrato = value; } }, metadata: _metadata }, _fecTrato_initializers, _fecTrato_extraInitializers);
        __esDecorate(null, null, _vendedor_decorators, { kind: "field", name: "vendedor", static: false, private: false, access: { has: obj => "vendedor" in obj, get: obj => obj.vendedor, set: (obj, value) => { obj.vendedor = value; } }, metadata: _metadata }, _vendedor_initializers, _vendedor_extraInitializers);
        __esDecorate(null, null, _planPagoVendedor_decorators, { kind: "field", name: "planPagoVendedor", static: false, private: false, access: { has: obj => "planPagoVendedor" in obj, get: obj => obj.planPagoVendedor, set: (obj, value) => { obj.planPagoVendedor = value; } }, metadata: _metadata }, _planPagoVendedor_initializers, _planPagoVendedor_extraInitializers);
        __esDecorate(null, null, _refinanciacion_decorators, { kind: "field", name: "refinanciacion", static: false, private: false, access: { has: obj => "refinanciacion" in obj, get: obj => obj.refinanciacion, set: (obj, value) => { obj.refinanciacion = value; } }, metadata: _metadata }, _refinanciacion_initializers, _refinanciacion_extraInitializers);
        __esDecorate(null, null, _cancelacionAnticipada_decorators, { kind: "field", name: "cancelacionAnticipada", static: false, private: false, access: { has: obj => "cancelacionAnticipada" in obj, get: obj => obj.cancelacionAnticipada, set: (obj, value) => { obj.cancelacionAnticipada = value; } }, metadata: _metadata }, _cancelacionAnticipada_initializers, _cancelacionAnticipada_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        CuotasPagadasEntity = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return CuotasPagadasEntity = _classThis;
})();
exports.CuotasPagadasEntity = CuotasPagadasEntity;
